// frontend/src/components/FileDropzone.tsx
import {useRef, useState} from 'react'
import styles from './FileDropzone.module.css'

interface FileDropzoneProps {
    onFileSelected: (file: File) => void
}

export default function FileDropzone({onFileSelected}: FileDropzoneProps) {
    const [isDragging, setIsDragging] = useState(false)
    const fileInputRef = useRef<HTMLInputElement>(null)

    const handleDragOver = (e: React.DragEvent) => {
        e.preventDefault()
        setIsDragging(true)
    }

    const handleDragLeave = () => {
        setIsDragging(false)
    }

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault()
        setIsDragging(false)
        const files = e.dataTransfer.files
        if (files && files.length > 0) {
            onFileSelected(files[0])
        }
    }

    const handleClick = () => {
        fileInputRef.current?.click()
    }

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = e.target.files
        if (files && files.length > 0) {
            onFileSelected(files[0])
        }
    }

    return (
        <div
            className={`${styles.dropzone} ${isDragging ? styles.dragging : ''}`}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            onClick={handleClick}
        >
            <input
                ref={fileInputRef}
                type="file"
                accept="text/*"
                className={styles.input}
                onChange={handleFileChange}
            />
            <div className={styles.content}>
                <svg className={styles.icon} viewBox="0 0 24 24" fill="none" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                          d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/>
                </svg>
                <p className={styles.text}>
                    Drag and drop a log JSON file here, or click to select
                </p>
                <p className={styles.hint}>
                    Supports Android logcat JSON exports
                </p>
            </div>
        </div>
    )
}

// frontend/src/components/FileDropzone.vue
<script setup lang="ts">
import { ref } from 'vue'

const emit = defineEmits<{
  'file-selected': [file: File]
}>()

const isDragging = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)

function handleDragOver(event: DragEvent) {
  event.preventDefault()
  isDragging.value = true
}

function handleDragLeave() {
  isDragging.value = false
}

function handleDrop(event: DragEvent) {
  event.preventDefault()
  isDragging.value = false

  const files = event.dataTransfer?.files
  if (files && files.length > 0) {
    emit('file-selected', files[0])
  }
}

function handleClick() {
  fileInput.value?.click()
}

function handleFileChange(event: Event) {
  const target = event.target as HTMLInputElement
  const files = target.files
  if (files && files.length > 0) {
    emit('file-selected', files[0])
  }
}
</script>

<template>
  <div
    class="dropzone"
    :class="{ 'dropzone--dragging': isDragging }"
    @dragover="handleDragOver"
    @dragleave="handleDragLeave"
    @drop="handleDrop"
    @click="handleClick"
  >
    <input
      ref="fileInput"
      type="file"
      accept=".json"
      class="dropzone-input"
      @change="handleFileChange"
    />

    <div class="dropzone-content">
      <svg class="dropzone-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
      </svg>

      <p class="dropzone-text">
        Drag and drop a log JSON file here, or click to select
      </p>

      <p class="dropzone-hint">
        Supports Android logcat JSON exports
      </p>
    </div>
  </div>
</template>

<style scoped>
.dropzone {
  width: 100%;
  max-width: 500px;
  padding: 4rem 2rem;
  border: 2px dashed #ccc;
  border-radius: 8px;
  cursor: pointer;
  transition: border-color 0.2s, background-color 0.2s;
  text-align: center;
}

.dropzone:hover,
.dropzone--dragging {
  border-color: #4a90d9;
  background-color: rgba(74, 144, 217, 0.05);
}

.dropzone-input {
  display: none;
}

.dropzone-icon {
  width: 48px;
  height: 48px;
  color: #999;
  margin-bottom: 1rem;
}

.dropzone-text {
  font-size: 1.1rem;
  color: #333;
  margin: 0 0 0.5rem 0;
}

.dropzone-hint {
  font-size: 0.875rem;
  color: #666;
  margin: 0;
}
</style>
